version: '3'
services:
  postgres:
    image: postgres:13-alpine
    restart: no
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db

volumes:
  postgres-data:
